package staffsystem;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lcooper2
 */
public class addRelationship extends javax.swing.JFrame {

    Child child;
    ChildList childList;
    Relative relative;
    RelativeList relativeList;
    DBConnection connect;
    
    int childIndex;
    int relativeIndex;
    Object thisChild;
    Object thisRelative;
    String selectedChild;
    String selectedRelative;
    String relationToChild;
    String childID;
    String relativeID;
    String[] childInfo;
    String[] relativeInfo;
    
    
    /**
     * Creates new form addRelationship
     */
    public addRelationship() throws SQLException, ClassNotFoundException {
        initComponents();
        getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
        
        connect = new DBConnection();
        this.connect.dbConnect();
        
        setChildList();
        setRelativeList();
    }
    
    public void setChildList() throws SQLException{
        this.childList = this.connect.viewAllChildren();
        jListChildren.setListData(this.childList.getAllChildren());
        jListChildren.setSelectedIndex(0);
        setSelectedChild();
    }
    
    public void searchChildList() throws SQLException{
        this.childList = this.connect.searchAllChildren(jTextFieldSearchChild.getText());
        jListChildren.setListData(this.childList.getAllChildren());
        jListChildren.setSelectedIndex(0);
        setSelectedChild();
    }
    
    public void setSelectedChild(){
        childIndex = jListChildren.getSelectedIndex();
        thisChild = jListChildren.getModel().getElementAt(childIndex);
        selectedChild = thisChild.toString();
        childInfo = selectedChild.split(": ");
        child = this.childList.getChildAt(childInfo[0]);
        jTextFieldChildName.setText(child.getFirstName() + " " + child.getSurname());
    }
    
    public void setRelativeList() throws SQLException{
        this.relativeList = this.connect.viewAllRelatives();
        jListRelatives.setListData(this.relativeList.getAllRelatives());
        jListRelatives.setSelectedIndex(0);
        setSelectedRelative();
    }
    
    public void searchRelativeList() throws SQLException{
        this.relativeList = this.connect.searchAllRelatives(jTextFieldSearchRelative.getText());
        jListRelatives.setListData(this.relativeList.getAllRelatives());
        jListRelatives.setSelectedIndex(0);
        setSelectedRelative();
    }
    
    public void setSelectedRelative(){
        relativeIndex = jListRelatives.getSelectedIndex();
        thisRelative = jListRelatives.getModel().getElementAt(relativeIndex);
        selectedRelative = thisRelative.toString();
        relativeInfo = selectedRelative.split(": ");
        relative = this.relativeList.getRelativeAt(relativeInfo[0]);
        jTextFieldRelativeName.setText(relative.getFirstName() + " " + relative.getSurname());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHeading = new javax.swing.JLabel();
        jLabelRelativeName = new javax.swing.JLabel();
        jTextFieldRelativeName = new javax.swing.JTextField();
        jLabelRelationship = new javax.swing.JLabel();
        jComboBoxRelationship = new javax.swing.JComboBox();
        jLabelAddRelationship = new javax.swing.JLabel();
        jLabelCancel = new javax.swing.JLabel();
        jLabelChild = new javax.swing.JLabel();
        jTextFieldSearchChild = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListChildren = new javax.swing.JList();
        jLabelRelative = new javax.swing.JLabel();
        jTextFieldSearchRelative = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListRelatives = new javax.swing.JList();
        jLabelChildName = new javax.swing.JLabel();
        jTextFieldChildName = new javax.swing.JTextField();
        jLabelLegalContact = new javax.swing.JLabel();
        jTextFieldLegalContact = new javax.swing.JTextField();
        jLabelSearchRelative = new javax.swing.JLabel();
        jLabelSearchChild = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelHeading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/relationshipHeading.png"))); // NOI18N

        jLabelRelativeName.setText("Relative Name");

        jLabelRelationship.setText("Relationship");

        jComboBoxRelationship.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Father", "Mother", "Step-Father", "Father-in-law", "Step-Mother", "Mother-in-law", "GrandMother", "Grandfather", "Brother", "Sister", "Auntie", "Uncle", "Cousin" }));

        jLabelAddRelationship.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addRelationship_button.png"))); // NOI18N
        jLabelAddRelationship.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelAddRelationshipMousePressed(evt);
            }
        });

        jLabelCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_button.png"))); // NOI18N
        jLabelCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCancelMouseClicked(evt);
            }
        });

        jLabelChild.setText("Child");

        jTextFieldSearchChild.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchChildKeyReleased(evt);
            }
        });

        jListChildren.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListChildren.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jListChildrenMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jListChildren);

        jLabelRelative.setText("Relative");

        jTextFieldSearchRelative.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchRelativeKeyReleased(evt);
            }
        });

        jListRelatives.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListRelatives.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jListRelativesMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jListRelatives);

        jLabelChildName.setText("Child Name");

        jLabelLegalContact.setText("Legal Contact");

        jLabelSearchRelative.setText("Search");

        jLabelSearchChild.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabelHeading)
                        .addGap(0, 291, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelChild)
                            .addComponent(jLabelRelative))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelSearchRelative)
                                            .addComponent(jLabelSearchChild))
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldSearchRelative))
                                    .addComponent(jScrollPane2))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelCancel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelAddRelationship))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelRelativeName)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextFieldRelativeName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelRelationship)
                                                .addComponent(jLabelChildName)
                                                .addComponent(jLabelLegalContact))
                                            .addGap(29, 29, 29)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldChildName)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jComboBoxRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextFieldLegalContact, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(0, 0, Short.MAX_VALUE)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldSearchChild, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHeading)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRelativeName)
                            .addComponent(jTextFieldRelativeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRelative))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRelationship)
                            .addComponent(jComboBoxRelationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelChildName)
                            .addComponent(jTextFieldChildName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLegalContact)
                            .addComponent(jTextFieldLegalContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldSearchRelative, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSearchRelative))
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSearchChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSearchChild)
                            .addComponent(jLabelChild))))
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelAddRelationship)
                    .addComponent(jLabelCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        homePage home = null;
        this.dispose();
        try {
            home = new homePage();
        } catch (SQLException ex) {
            Logger.getLogger(addRelationship.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(addRelationship.class.getName()).log(Level.SEVERE, null, ex);
        }
        home.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void jLabelCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCancelMouseClicked
        homePage home = null;
        this.dispose();
        try {
            home = new homePage();
        } catch (SQLException ex) {
            Logger.getLogger(addRelationship.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(addRelationship.class.getName()).log(Level.SEVERE, null, ex);
        }
        home.setVisible(true);
    }//GEN-LAST:event_jLabelCancelMouseClicked

    private void jLabelAddRelationshipMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAddRelationshipMousePressed
        addRelationship(child.getChildID(), relative.getRelativeID(), jComboBoxRelationship.getSelectedItem(), jTextFieldLegalContact.getText());
        homePage home = null;
        this.dispose();
        try {
            home = new homePage();
        } catch (SQLException ex) {
            Logger.getLogger(addRelationship.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(addRelationship.class.getName()).log(Level.SEVERE, null, ex);
        }
        home.setVisible(true);
    }//GEN-LAST:event_jLabelAddRelationshipMousePressed

    private void jListRelativesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListRelativesMousePressed
        setSelectedRelative();
    }//GEN-LAST:event_jListRelativesMousePressed

    private void jListChildrenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListChildrenMousePressed
        setSelectedChild();
    }//GEN-LAST:event_jListChildrenMousePressed

    private void jTextFieldSearchRelativeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchRelativeKeyReleased
        try {
            searchRelativeList();
        } catch (SQLException ex) {
            Logger.getLogger(addRelationship.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldSearchRelativeKeyReleased

    private void jTextFieldSearchChildKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchChildKeyReleased
        try {
            searchChildList();
        } catch (SQLException ex) {
            Logger.getLogger(addRelationship.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldSearchChildKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addRelationship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addRelationship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addRelationship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addRelationship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new addRelationship().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(addRelationship.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(addRelationship.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void addRelationship(int childIDNum, int relativeIDNum, Object relation, String legalContact){
        relationToChild = relation.toString();
        childID = childIDNum + "";
        relativeID = relativeIDNum + "";
        connect.addRelationship(childID, relativeID, relationToChild, legalContact);
    }
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxRelationship;
    private javax.swing.JLabel jLabelAddRelationship;
    private javax.swing.JLabel jLabelCancel;
    private javax.swing.JLabel jLabelChild;
    private javax.swing.JLabel jLabelChildName;
    private javax.swing.JLabel jLabelHeading;
    private javax.swing.JLabel jLabelLegalContact;
    private javax.swing.JLabel jLabelRelationship;
    private javax.swing.JLabel jLabelRelative;
    private javax.swing.JLabel jLabelRelativeName;
    private javax.swing.JLabel jLabelSearchChild;
    private javax.swing.JLabel jLabelSearchRelative;
    private javax.swing.JList jListChildren;
    private javax.swing.JList jListRelatives;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldChildName;
    private javax.swing.JTextField jTextFieldLegalContact;
    private javax.swing.JTextField jTextFieldRelativeName;
    private javax.swing.JTextField jTextFieldSearchChild;
    private javax.swing.JTextField jTextFieldSearchRelative;
    // End of variables declaration//GEN-END:variables
}
